### ISSUE TITLE
Not runnable on ARM64

### ISSUE THREAD

**Issue by lucyllewy** [degville/snap-yt-dlp#1]
I've tried to run this on my m1-based Mac in a vmWare VM of Ubuntu 22.04. Unfortunately, it doesn't launch with Python reporting a shared library issue with the Cryptodome module.

On investigation it seems that the Cryptodome python module has shipped x86_64 shared-object libraries (`.so` files) which are obviously incompatible with the ARM64 environment. I haven't looked to see if Cryptodome has any ARM64 distributions to provide a fix yet.

I suspect that armhf suffers the same fate but haven't verified that.

**Comment by degville** [comment]
Hello - thanks for reporting this.  I've just tried the same on my Pi and get the same error. I had thought it was okay, as there's a few hundred people with an ARM build installed, but it's now likely broken for them too. I'll play with the yaml on my own M1 and see if I can find a solution.

**Comment by degville** [comment]
I've just built an arm64 snap, and tried this again on arm64 (M1, Parallels, Ubuntu 23.04) and it appears to now be working. This snap is currently in the beta channel.

**Comment by eslerm** [comment]
Thanks for the recent updates.

This repo built and runs well for me on an arm64 M2 running 23.10 Ubuntu Asahi.

**Comment by degville** [comment]
I'm closing this as the ARM64 is still working for me. Let me know if there are any other problems.
